name: Build and publish the oraclelinux8-compat:8-slim compatibility image

# Builds are triggered either by:
#   - a push on the master branch with changes in this file.
#   - a manual trigger of the workflow using the API.
# Images are built for both amd64 and arm64 architectures
# The build-and-push-dev-images workflow will be triggered for the developer
# images based on oraclelinux8-compat:8-slim
on:
  push:
    branches:
      - main
      - workflow
    paths:
      - 'OracleLinuxDevelopers/oraclelinux8/compat/**'
      - '.github/workflows/build-and-push-dev-compat.yml'
  workflow_dispatch:

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: locals
        id: locals
        working-directory: OracleLinuxDevelopers/oraclelinux8
        run: |
          echo "::set-output name=repository_owner::$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')"
          echo "::set-output name=date_stamp::$(date +'%Y%m%d')"
          readarray -t lang < <(grep -l '^FROM.*oraclelinux8-compat:8-slim'  */*/Dockerfile | sed -e 's!/.*!!' | sort -u)
          echo "::set-output name=lang::${lang[*]}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image - amd64
        uses: docker/build-push-action@v2
        with:
          context: OracleLinuxDevelopers/oraclelinux8/compat/8-slim
          platforms: linux/amd64
          push: true
          tags: |
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-${{ steps.locals.outputs.date_stamp }}-amd64"
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-amd64"

      - name: Build image - arm64
        uses: docker/build-push-action@v2
        with:
          context: OracleLinuxDevelopers/oraclelinux8/compat/8-slim
          platforms: linux/arm64
          push: true
          tags: |
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-${{ steps.locals.outputs.date_stamp }}-arm64"
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-arm64"

      - name: Manifest
        run: |
          docker buildx imagetools create --tag \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-${{ steps.locals.outputs.date_stamp }}" \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-${{ steps.locals.outputs.date_stamp }}-amd64" \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-${{ steps.locals.outputs.date_stamp }}-arm64"
          docker buildx imagetools create --tag \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim" \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-amd64" \
            "ghcr.io/${{ steps.locals.outputs.repository_owner }}/oraclelinux8-compat:8-slim-arm64"

      - name: Trigger dependencies
        uses: benc-uk/workflow-dispatch@v1
        if: ${{ steps.locals.outputs.lang != '' }}
        with:
          workflow: Build and publish Oracle Linux developer container images to GitHub Container Registry
          token: ${{ secrets.PERSONAL_TOKEN }}
          inputs: '{ "ol": "oraclelinux8", "lang": "${{ steps.locals.outputs.lang }}" }'
